// Generated by CoffeeScript 1.10.0
(function() {
  var adapter, fs, jref, json, ohmygraph, omg, opts;

  adapter = require('ohmygraph-madeapi-adapter');

  ohmygraph = require('ohmygraph');

  jref = require('json-ref-lite');

  fs = require('fs');

  json = JSON.parse(fs.readFileSync(__dirname + '/structure.json').toString());

  opts = {};

  opts.reftoken = '@ref';

  opts.pathtoken = '@';

  opts.refprefix = 'rest.';

  opts.exportfunctions = true;

  opts.exportfunctions = false;

  json = adapter.parse(json, '1.0', opts);

  omg = ohmygraph.create(json);

  console.log(omg.export_functions());

}).call(this);
