// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = (function() {
    this.parse = function(json, version, reftoken, pathtoken) {
      var k, obj, parser, ref1, v;
      if (reftoken == null) {
        reftoken = '$';
      }
      if (pathtoken == null) {
        pathtoken = '#';
      }
      obj = {};
      if (this.v[version] == null) {
        throw new Error({
          msg: "version " + version + " not supported"
        });
      }
      parser = this.v[version];
      ref1 = json.structure;
      for (k in ref1) {
        v = ref1[k];
        obj[k] = {};
        if (v.relations != null) {
          parser.get_relations(v.relations, obj[k]);
        }
        if (v.relations != null) {
          parser.get_properties(v, obj[k]);
        }
      }
      return obj;
    };
    this.v = {
      '1.0': {
        get_relations: function(relations, obj) {
          var ref, relation, results, rv;
          if (obj.output == null) {
            obj.output = [];
          }
          results = [];
          for (relation in relations) {
            rv = relations[relation];
            ref = {};
            ref[reftoken + "ref"] = pathtoken + "/" + relation;
            results.push(obj.output.push(ref));
          }
          return results;
        },
        get_properties: function(entity, obj) {
          var name, pv, ref1, results;
          if (obj.properties == null) {
            obj.properties = {};
          }
          if (entity.payload == null) {
            return;
          }
          ref1 = entity.payload;
          results = [];
          for (name in ref1) {
            pv = ref1[name];
            results.push(obj.properties[name] = pv);
          }
          return results;
        }
      }
    };
    return this;
  }).apply({});

}).call(this);
